### ISSUE TITLE
Wrong constraints in Memory table

### ISSUE THREAD

**Issue by la10736** [aszepieniec/stark-brainfuck#39]
Hi, thanks for the really interesting blog.

I found some minor issue in _Memory Table_ paragraph. 

- `(clk - 1 - clk*)(mv -mv*)` should be `(clk + 1 - clk*)(mv -mv*)`
- enforce both `(mp - mp*) mv*` and `(mp -mp*)(mv - mv*)` imply that also `mv` should be 0 every time that `mp` change (and not just `mv*`). I noted that in the python code you removed the `(mp -mp*)(mv - mv*)` constrain

**Comment by la10736** [comment]
Ok I found the right version in the Rust code

`(mp* - mp - 1)(mv* - mv)(clk* - clk - 1)`

```rust
        // 2. if memory pointer does not increase, then memory value can change only if cycle counter increases by one
        //        <=>. MP*=MP => (MV*=/=MV => CLK*=CLK+1)
        //        <=>. MP*=/=MP \/ (MV*=/=MV => CLK*=CLK+1)
        // (DNF:) <=>. MP*=/=MP \/ MV*=MV \/ CLK*=CLK+1
        // polynomials += [(address_next - address - one) *
        //                 (value_next - value) * (cycle_next - cycle - one)]
        polynomials.push(
            (address_next.clone() - address.clone() - one.clone())
                * (value_next.clone() - value)
                * (cycle_next - cycle - one),
        );
```

**Comment by Sword-Smith** [comment]
Thanks for the issue. The memory table got somewhat more complex (and longer) due to the attack explained here. Maybe it has your interest. https://github.com/TritonVM/triton-vm/issues/12

**Comment by aszepieniec** [comment]
Closing this issue because the new constraints, and the reason for their update, is explained in [Part V](https://aszepieniec.github.io/stark-brainfuck/attack).
